AWSTemplateFormatVersion: "2010-09-09"
Description: "stackName: acm. AWS::CertificateManager::Certificate"

Parameters:
  Domain:
    Type: String
    Description: Validation Domain
    Default: example.com
  HostedZoneId:
    Type: String
    Description: HostedZoneId
    Default: Z012345689ABCDEFG

Resources:
  ACM:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref Domain
      DomainValidationOptions:
        - DomainName: !Ref Domain
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

Outputs:
  ACMArn:
    Description: Output Export AWS::CertificateManager::Certificate.Arn
    Value: !Ref ACM
    Export:
      Name: acm-arn
