AWSTemplateFormatVersion: "2010-09-09"
Description: "stackName: secretsmanager. AWS::SecretsManager::Secret"

Parameters:
  CloudfrontCustomHeaderName:
    Type: String
    Description: CloudFront Custom Header Name
    Default: X-Custom-Header
    NoEcho: true
  CloudfrontCustomHeaderValue:
    Type: String
    Description: CloudFront Custom Header Value
    NoEcho: true

Resources:
  CFCustomHeader:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: CloudFront custom headers to limit ALB connections
      KmsKeyId: alias/aws/secretsmanager
      Name: cf-custom-header
      SecretString: !Sub '{"CLOUDFRONT_CUSTOM_HEADER_NAME":"${CloudfrontCustomHeaderName}","CLOUDFRONT_CUSTOM_HEADER_VALUE":"${CloudfrontCustomHeaderValue}"}'
