apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: es-sample-cert
spec:
  secretName: es-sample-cert-secret
  issuerRef:
    name: es-sample-letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - '*.ki-ta.blog'
