apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: es-sample-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sample@gmail.com
    privateKeySecretRef:
      name: es-sample-letsencrypt-secret
    solvers:
    - selector:
        dnsZones:
        - '*.ki-ta.blog'
      dns01:
        route53:
          hostedZoneID: Z012345689ABCDEFG
          accessKeyIDSecretRef:
            name: route53-credentials-secret
            key: access-key
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: secret-key
          region: ap-northeast-1
